// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUwFHINISRuv6xR2meEofa8nhFdPDWFRQ',
    appId: '1:265559642199:web:8aca505a82fde571715312',
    messagingSenderId: '265559642199',
    projectId: 'fast-tende',
    authDomain: 'fast-tende.firebaseapp.com',
    storageBucket: 'fast-tende.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzR3-wreMjUphBFT91BapmWiO37Mk0ZgA',
    appId: '1:265559642199:android:38d4bb42d130a6af715312',
    messagingSenderId: '265559642199',
    projectId: 'fast-tende',
    storageBucket: 'fast-tende.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1CQap_jxdCpCGYfx6By4PNffhpIxfe2w',
    appId: '1:265559642199:ios:aa11266494678ae1715312',
    messagingSenderId: '265559642199',
    projectId: 'fast-tende',
    storageBucket: 'fast-tende.appspot.com',
    iosClientId: '265559642199-nvcguccrko3f8at43h1hah6d55ecbilt.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastTendeDoctorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1CQap_jxdCpCGYfx6By4PNffhpIxfe2w',
    appId: '1:265559642199:ios:aa11266494678ae1715312',
    messagingSenderId: '265559642199',
    projectId: 'fast-tende',
    storageBucket: 'fast-tende.appspot.com',
    iosClientId: '265559642199-nvcguccrko3f8at43h1hah6d55ecbilt.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastTendeDoctorApp',
  );
}
